/* products table */
INSERT INTO products (name, price, botName, category, imgUrl, water, sun, temperature, description) VALUES 
("Cacti mix 2", 8.50, "Latin name", "Succulent", "assets/products/cacti-mix-2.png", 1, 2, 3, "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur sapiente, architecto, dignissimos molestiae vero harum, quo incidunt repellat ipsum adipisci quod. Nulla ipsam fugiat neque ducimus omnis? Delectus doloribus fugit amet esse enim harum deserunt ipsum, veritatis ipsa voluptate provident?"), 
("Athurium", 12.30, "Latin name", "Flower", "assets/products/athurium.png", 3, 1, 3, "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur sapiente, architecto, dignissimos molestiae vero harum, quo incidunt repellat ipsum adipisci quod. Nulla ipsam fugiat neque ducimus omnis? Delectus doloribus fugit amet esse enim harum deserunt ipsum, veritatis ipsa voluptate provident?"),
("Aloe vera", 10.50, "Latin name", "Succulent", "assets/products/aloe-vera.png", 1, 1, 1, "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur sapiente, architecto, dignissimos molestiae vero harum, quo incidunt repellat ipsum adipisci quod. Nulla ipsam fugiat neque ducimus omnis? Delectus doloribus fugit amet esse enim harum deserunt ipsum, veritatis ipsa voluptate provident?"), 
("Fittonia", 9.50, "Latin name", "Leafy", "assets/products/fittonia.png", 2, 2, 3, "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur sapiente, architecto, dignissimos molestiae vero harum, quo incidunt repellat ipsum adipisci quod. Nulla ipsam fugiat neque ducimus omnis? Delectus doloribus fugit amet esse enim harum deserunt ipsum, veritatis ipsa voluptate provident?"), 
("Pot 12cm", 5.50, "", "Accessory", "assets/products/pot-2.png", 0, 0, 0, "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur sapiente, architecto, dignissimos molestiae vero harum, quo incidunt repellat ipsum adipisci quod. Nulla ipsam fugiat neque ducimus omnis? Delectus doloribus fugit amet esse enim harum deserunt ipsum, veritatis ipsa voluptate provident?"), 
("Orchidea", 10.20, "Latin name", "Flower", "assets/products/orchidea.png", 1, 2, 3, "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur sapiente, architecto, dignissimos molestiae vero harum, quo incidunt repellat ipsum adipisci quod. Nulla ipsam fugiat neque ducimus omnis? Delectus doloribus fugit amet esse enim harum deserunt ipsum, veritatis ipsa voluptate provident?"),
("Pot 10x5cm", 4.50, "", "Accessory", "assets/products/pot-green.png", 0, 0, 0, "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur sapiente, architecto, dignissimos molestiae vero harum, quo incidunt repellat ipsum adipisci quod. Nulla ipsam fugiat neque ducimus omnis? Delectus doloribus fugit amet esse enim harum deserunt ipsum, veritatis ipsa voluptate provident?"),
("Pot 12cm", 5.50, "", "Accessory", "assets/products/pot-stone.png", 0, 0, 0, "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur sapiente, architecto, dignissimos molestiae vero harum, quo incidunt repellat ipsum adipisci quod. Nulla ipsam fugiat neque ducimus omnis? Delectus doloribus fugit amet esse enim harum deserunt ipsum, veritatis ipsa voluptate provident?"),
("Cacti mix", 9.30, "Latin name", "Succulent", "assets/products/cacti-mix.png", 1, 2, 3, "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur sapiente, architecto, dignissimos molestiae vero harum, quo incidunt repellat ipsum adipisci quod. Nulla ipsam fugiat neque ducimus omnis? Delectus doloribus fugit amet esse enim harum deserunt ipsum, veritatis ipsa voluptate provident?"),
("Violet", 10.00, "Latin name", "Flower", "assets/products/violet.png", 1, 2, 3, "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur sapiente, architecto, dignissimos molestiae vero harum, quo incidunt repellat ipsum adipisci quod. Nulla ipsam fugiat neque ducimus omnis? Delectus doloribus fugit amet esse enim harum deserunt ipsum, veritatis ipsa voluptate provident?"),
("Snake plant", 14.20, "Latin name", "Leafy", "assets/products/snake-plant.png", 3, 2, 2, "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur sapiente, architecto, dignissimos molestiae vero harum, quo incidunt repellat ipsum adipisci quod. Nulla ipsam fugiat neque ducimus omnis? Delectus doloribus fugit amet esse enim harum deserunt ipsum, veritatis ipsa voluptate provident?"),
("Monstera deliciosa", 21.50, "Latin name", "Leafy", "assets/products/monstera-deliciosa.png", 1, 2, 3, "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur sapiente, architecto, dignissimos molestiae vero harum, quo incidunt repellat ipsum adipisci quod. Nulla ipsam fugiat neque ducimus omnis? Delectus doloribus fugit amet esse enim harum deserunt ipsum, veritatis ipsa voluptate provident?"),
("Sunflower", 4.50, "", "", "", 1, 2, 3, "");


/* tips table */
INSERT INTO tips (title, imgUrl, text) VALUES
("Propagate mint cuttings in water", "assets/tips/mint-propagation.png", "Take cuttings that are 3-5 inches long so that there is plenty of area on the stem for roots to grow. Longer stems are easier to propagate than short ones since there will be more places for roots to grow. Before propagating the cuttings, remove 2-3 sets of leaves from the bottom of the stem. Now all you need to do is put them into a vase just like you would do with cut flowers. Make sure that none of the leaves are touching the water, because those will rot."),
("Spring-blooming bulbs", "assets/tips/tulips.png", "Plant spring-blooming bulbs, such as tulips, fritillarias, ornamental alliums, and crocuses, in the fall before the ground freezes. In general, place the bulb in a hole that's two to three times the depth of the bulb. While most hardy bulbs you only need to plant once, and they'll keep coming up year after year, note that hybrid tulips are an exception to this rule. It's best to pull them up when they are done blooming and replant new tulip bulbs each fall, or choose species tulips that become perennial."),
("Don't forget to add compost", "assets/tips/compost.png", "Fertilizer is not the answer to growing the best plants; soil quality is. Add organic amendments such as compost and well-aged manure to your soil. The best soil structure is crumbly, easy to dig, accepts water easily, and is loose enough to provide oxygen for plant roots. If you choose to use fertilizer, use an organic one to add nitrogen, phosphate, and potash (the form of potassium plants can use)"),
("Make your pot fit the plant", "assets/tips/pick-pot.png", "When choosing a pot, make sure to consider its material, size, and drainage capability. Use a pot that’s proportional to your plant's current size—not more than a few inches wider in diameter than your plant’s root mass. Once the plant outgrows its home, you can transplant it into a larger pot. If you instead start a plant in a larger pot than necessary, its roots won't be able to absorb moisture fast enough as it drains through the soil.");
